### ISSUE TITLE
Missing Task system - Tasks for player to do throughout the day (everyday)

### ISSUE THREAD

**Issue by michaeltranxd** [michaeltranxd/Work-Life-Balance#9]
Separate tasks than the current tasks in a database.
- Required to do it
- Adds struggle to player for time management
- Balance unforeseen circumstances with staying healthy
- Perhaps a random event?

**Comment by michaeltranxd** [comment]
Spancer worked on basic task system. Will need more work on tasks

**Comment by spancerrr** [comment]
The Task system is done. The player will get different tasks for each day and the tasks depend on the day of the week. If the player doesn't finish the task before recap, stats will be change accordingly. There are total of 9 tasks, all the unfinished tasks will be add to the next day's task list expect "Go to work" and "Work from home".
